{{-- this is the top navbar automatically created by laravel --}}
@extends('layouts.app')

{{-- adding things after the navbar --}}
@section('content')
<div class="container ">

    <div class="row justify-content-center container1">
        <div class="col-md-12 ">
            <div class="row">
                <div class="col-md-6 ">
                    <div class="svg">
                    <img class="img img-set-logo img-fluid"  src="{{ asset('/images/undraw_real_time_collaboration_c62i.svg')}}" alt="" />
                    </div> 
                </div>
                <div class="col-md-6" >
                    <div>
                        <img class="logo" src="{{ asset('/images/PRONTO_LOGO.png')}}" alt="" />
                    </div>
                    <div class="text-center mt-3 mb-4" >
                        <h2 class="ml-3">SIGN IN</h2>
                    </div>
                    
                    <div class=" login-container">
                        <form method="POST" action="{{ route('login') }}">
                        @csrf
                        {{-- email --}}
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        {{-- password --}}
                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        {{-- remember me, automatically generated by laravel--}}
                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>  
                            </div>
                        </div>

                        {{-- forgot password, redirecting to the view reset.blade.php inside auth/password --}}
                        <div class="form-group  mb-5" >
                            <div class="justify-content-center">
                                <button type="submit" class="btn">
                                    {{ __('Login') }}
                                </button>
                                <div class="forgotpass">
                                    @if (Route::has('password.request'))
                                    <a class=" btn-link btn-link-pass" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                                </div> 
                            </div>
                        </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
